# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Women Hack for Non-Profits
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We are Women Hack for Non-Profits, a community of tech enthusiasts dedicating 
  their time to open source projects aimed at non-profit organisations.
# baseurl:      "echesters.github.io/WHFNP-Website" # the subpath of your site, e.g. /blog
url:        "/echesters.github.io/WHFNP-Website" # the base hostname & protocol for your site
twitter_username:   whfnp
github_username:    echesters

# Build settings
markdown: kramdown